site_name: AI-CS Learning Guide
site_url: https://george-102.github.io/ai-cs-guide/
site_author: Christopher
site_description: a guide for learning AI-CS

repo_name: ai-cs-guide
repo_url: https://github.com/George-102/ai-cs-guide

copyright: Copyright &copy; 2026-present <a href="https://github.com/George-102" target="_blank" rel="noopener noreferrer">Christopher</a>

theme:
  name: material
  custom_dir: overrides  
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.svg
  apple-touch-icon-precomposed: images/favicon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - comments

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'deep purple'
      accent: 'pink'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep green'
      accent: 'lime'
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github # 右上角 GitHub 链接按钮的图标
    previous: material/arrow-left-circle # 自定义“上一页”图标
    next: material/arrow-right-circle  

  # 如果没有 overrides 文件夹，删除下面这行或注释掉
  # custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: AI-CS Learning Guide
          nav_translations:
            前言: Foreword
            如何使用这本指南: How to Use This Guide
            工具和方法: Tools and Methods
            AI基础与大模型: Foundation Models
            提示工程: Prompt Engineering
            提示工程指南: Prompt Engineering Guide
            AI辅助编程: AI Coding
            Python官方教程: Python official documentation
            科学上网: GFW
            Git: Git
            Docker: Docker
            LaTeX: LaTeX
            GNU Make: GNU Make
            VS Code: VS Code
            WSL: WSL
            Oh My Zsh: Oh My Zsh
            Stack Overflow: Stack Overflow
            Obsidian: Obsidian
            工作流: Workflow



  - search:
      lang:
        - zh
        - en
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/George-102/ai-cs-guide/

nav:
  - 前言: "index.md"
  - 工具和方法:
      - Scoop: "工具和方法/scoop.md"
      - 科学上网: "工具和方法/魔法.md"
      - Git: "工具和方法/Git.md"
      - Docker: "工具和方法/Docker.md"
      - LaTeX: "工具和方法/LaTeX.md"
      - GNU Make: "工具和方法/Make.md"
      - VS Code: "工具和方法/VSCode.md"
      - WSL: "工具和方法/WSL.md"
      - Vim: "工具和方法/Vim.md"
      - Oh My Zsh: "工具和方法/Zsh.md"
      - Stack Overflow: "工具和方法/StackOverflow.md"
      - Obsidian: "工具和方法/Obsidian.md"
      - 工作流: "工具和方法/工作流.md"
  - Python:
      - Python官方教程: "Python/Python官方文档.md"
  - 提示工程:
      - 提示工程指南: "提示工程/Prompt Engineering.md"