site_name: AI-CS Learning Guide
site_url: https://george-102.github.io/ai-cs-guide/
site_author: Christopher
site_description: a guide for learning AI-CS

repo_name: ai-cs-guide
repo_url: https://github.com/George-102/ai-cs-guide

copyright: Copyright &copy; 2026-present <a href="https://github.com/George-102" target="_blank" rel="noopener noreferrer">Christopher</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  # 如果没有 overrides 文件夹，删除下面这行或注释掉
  # custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: AI-CS Learning Guide
          nav_translations:
            前言: Foreword
            AI基础与大模型: Foundation Models
            提示工程: Prompt Engineering
            AI辅助编程: AI Coding

  - search:
      lang:
        - zh
        - en
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/George-102/ai-cs-guide/

nav:
  - 前言: "index.md"
  - AI基础与大模型:
    - AI基础: "AI基础与大模型/hello.md"
  - 提示工程:
    - AI基础: "AI基础与大模型/hello.md"
  - AI辅助编程:
    - AI基础: "AI基础与大模型/hello.md"